# lightning.pytorch==2.4.0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  n_dims: null
  input_keys:
  - flair
  - t1
  label_key: WMH
  in_channels: 1
  out_channels: 1
  base_channels: 8
  depth: 4
  use_transpose: false
  use_normalization: true
  final_activation:
    class_path: torch.nn.Identity
  use_sliding_window: false
  learning_rate: 0.001
  loss_fn: torch.nn.functional.mse_loss
data:
  include_keys:
  - flair
  - t1
  - WMH
  dataset: WMH
  data_dir_wmh: data/wmh
  data_dir_brats: data/BraTS
  data_mode: 2d
  batch_size: 8
  num_workers: 8
optimizer: null
lr_scheduler: null
ckpt_path: null
